Goddard-Fortran-Ecosystem/pFUnit

tests/core-tests/Test_XmlPrinter.F90
This bug has not caused problems because apparently all relevant
systems have xmllint installed.  The intent was to silently skip the
xmllint check when unavailable, but the wrong status flag was used on
Fortran's EXECUTE_COMMAND_LINE.
The problem was exposed when testing under travis which has a more
distilled environment.  A patch earlier today added xmllint to travis.
In theory it is no longer needed but it is probably better to allow
the extra check during automated testing.
=> Fixed bug in XML unit test.

ChangeLog, source/CMakeLists.txt
Not clear why exactly this COMMAND case needs quotes when others apparently do not.
=> Fixes #12.

.travis.yml, CMakeLists.txt, src/mpi/CMakeLists.txt, tests/core-tests/CMakeLists.txt, tests/mpi-tests/CMakeLists.txt
- Corrected MPI and OpenMP as cached BOOL cmake options.
- Added top-level "tests" target
. tests depends on executables defined in the various test subdirectories
- ctest now works as intended.
% cmake .. [-DMPI=YES]
% make
% make tests
% ctest
=> Fixes #19 - improved build.

CMakeLists.txt, source/XmlPrinter.F90, source/pFUnitPackage.F90, tests/Test_MockRepository.F90, tests/Test_XmlPrinter.F90
A branch for supporting the Cray Compiler Environment (CCE) existed on SourceForge but it has not been migrated. More than that it was quite elderly and had not been kept up to date with the trunk.
This branch re-implements those changes against the head of trunk and has been tested against an XC40. It has been tested not only with the Cray compiler but also Intel and GNU so it should not break anything else.
=> Support Cray Compiler Environment

Examples/Fixture/GNUmakefile, Examples/Fixture/tests/GNUmakefile, Examples/MPI_Halo/GNUmakefile, Examples/MPI_Halo/tests/GNUmakefile, Examples/MPI_SimpleParameterizedTest/GNUmakefile, Examples/MPI_SimpleParameterizedTest/tests/GNUmakefile, Examples/ParameterizedTest/GNUmakefile, Examples/ParameterizedTest/tests/GNUmakefile, Examples/Robust/GNUmakefile, Examples/Robust/tests/GNUmakefile, Examples/Simple/GNUmakefile, Examples/Simple/tests/GNUmakefile, bin/pFUnitParser.py, bin/parseDirectiveArgs.py, bin/tests/expectedOutputs/MpiParameterizedTestCaseC.F90, bin/tests/expectedOutputs/MpiTestCaseB.F90, bin/tests/expectedOutputs/ParameterizedTestCaseB.F90, bin/tests/expectedOutputs/TestA.F90, bin/tests/expectedOutputs/TestCaseA.F90, bin/tests/expectedOutputs/beforeAfter.F90, bin/tests/expectedOutputs/simple.F90, bin/tests/inputs/MpiParameterizedTestCaseC.pf, bin/tests/inputs/MpiTestCaseB.pf, bin/tests/inputs/ParameterizedTestCaseB.pf, bin/tests/inputs/TestA.pf, bin/tests/inputs/TestCaseA.pf, bin/tests/runTests.sh, bin/tests/testParser.py, include/CMakeLists.txt, include/CRAY.mk
The Fortran preprocessor integrated with the Cray compiler does not recognise the `#line` directives output by pFUnitParser.py. The compiler itself does recognise linemarkers (`#<line number> ...`) as produced by preprocessors.
This change provides a switch "-markers" which tells pFUnitParser.py to use linemarkers instead of `#line` directives. Thus the user can choose the appropriate behaviour for their compiler.
Testing is ongoing so this change shouldn't go on trunk yet but I thought you should get early sight of it.
While I was at it I discovered that the various tests in "bin/tests" no longer reflected reality. They have been fixed and updated in line with this branch.
This change represents the end of any pretence at supporting Python 2.6. There were already a few non-compatible …
=> pFUnitParser now provides a "-markers" option to use linemarkers rather than #line directives

tests/core-tests/CMakeLists.txt
Just showed up and is unrelated to recent changes.   MockListener.F90 is
used in 2 libraries and apparently Travis ends up trying to compile
both copies simultaneousl and steps on itself.
=> Attempting to fix cmake race condition.

src/core/CMakeLists.txt, src/core/FUnit.F90, src/core/NameFilter.F90, src/core/TestFilter.F90, src/core/TestRunner.F90, src/core/TestSuite.F90, src/mpi/pFUnit.F90, tests/core-tests/CMakeLists.txt, tests/core-tests/Test_LiteralPattern.pf, tests/core-tests/Test_NameFilter.pf, tests/core-tests/Test_TestSuite.F90, tests/core-tests/serial_tests.F90, tests/core-tests/testSuites.inc, tests/mpi-tests/parallel_tests.F90
Created a family of filter classes that can be used to prune a test
suite.  For now just a NameFilter that keeps names that contain a
substring.   Later, more regexp capabilities will be added.
* added fArgParse option for debug
* added fArgParse option for filter
usage: ./tests/core-tests/new_tests.x [-h][-d][-f FILTER]
optional arguments:
-h, --help                 This message.
-d, --debug, --verbose     make output more verbose
-f, --filter               only run tests that match FILTER
Now have fArgParse options for debug and filter.
=> Fixes #38 - run just one test.

.travis.yml, CMakeLists.txt, src/CMakeLists.txt, src/mpi/CMakeLists.txt, tests/CMakeLists.txt, tests/mpi-tests/CMakeLists.txt
Build now uses find_package() and builds with MPI if installation is
found.  -DSKIP_MPI=YES can be used to override if MPI is _not_
desired.
Note that this is _NOT_ backward compatible with pFUnit 3.x.
=> Improved use of find_package(MPI).

CMakeLists.txt, include/PreprocessMacro.cmake, tests/CMakeLists.txt, tests/core-tests/CMakeLists.txt, tests/hamcrest-tests/CMakeLists.txt, tests/mpi-tests/CMakeLists.txt
Note that this macro is inconsistent with the one in the cmake config
file for external projects and additional thought is needed.
=> Now use single macro for preprocessing pfunit tests sources.

src/core/CMakeLists.txt, src/core/asserts/Assert.F90, src/core/asserts/Assert_Complex.tmpl, tests/core-tests/CMakeLists.txt, tests/core-tests/Test_AssertEqual_Complex.pf, tests/core-tests/Test_AssertEqual_Real.pf, tests/core-tests/testSuites.inc
Apparently I had forgotten to go back and create an include file that
USEs all of the generated asserts for various ranks in the top Asssert
module.  The tests generally directly used the specific rank modules,
which is why this was not detected sooner.
This commit also now includes some tests for ComplexAssert.  These are
hardly complete, but the code may be ok, as it is derived from the
Real case.
=> Fixed a few important deficiencies in new assert templates.

.travis.yml, CMakeLists.txt
The other distribution uses a flavor of cmake that is too old.
=> Updating travis to xenial distribution.

bin/funit/CMakeLists.txt, cmake/PFUNITConfig.cmake.in, include/CMakeLists.txt, include/add_pfunit_ctest.cmake, include/add_pfunit_sources.cmake, tests/CMakeLists.txt, tests/funit-core/CMakeLists.txt
Created a function add_pfunit_ctest() which takes a number of keyword
arguments and attempts to build an executable and ctest test from a
collection of test sources and additional sources.
Also fixed a few minor issues with the install step that were exposed
when attempting to exercise this new capability.
Note: this version should be considered preliminary.  More options are
needed, and not all existing options have been tested (e.g. MPI).
=> CMake support for projects that use CMake.

bin/funit/pFUnitParser.py
Copying polymorphic object into previously allocated instance (of different actual type) causes invalid writes/reads in some versions of gfortran. Workaround is to use `allocate(t, source=x)` instead of `t = x`.  Also need to possibly deallocate object first.
=> Workaround for bug in some versions of gfortran when copying objects

CMakeLists.txt, src/funit/CMakeLists.txt, src/funit/core/CMakeLists.txt, src/funit/core/ExceptionList.F90, src/funit/core/TestFailure.F90, src/pfunit/core/MpiContext.F90, src/pfunit/core/MpiTestCase.F90, src/pfunit/core/MpiTestParameter.F90, tests/CMakeLists.txt, tests/funit-core/CMakeLists.txt, tests/funit-core/serial_tests.F90, tests/pfunit/Test_MPI_stub.pf, tests/pfunit/Test_MpiException.F90, tests/pfunit/Test_MpiTestCase.F90, tests/pfunit/parallel_tests.F90
- Also corrected/updated OpenMP issues.
Note that OpenMP is not activated for NAG.  The problem is in
find_package(OpenMP).
- Eliminated various compiler warnings in MPI subdirs.
=> Fixes #108.  CMake options.

.gitattributes
Ideally we could highlight pFUnit annotations - but this appears to be
very difficult.
=> Fixes #108. Highlight .pf files as Fortran syntax.

cmake/CheckFortranSource.cmake
Contribution from @jurnix.
Still not entirely certain why this issue is triggered by an older
gfortran, while still passing all of the checks.   But this at least
eliminates worrisome cmake errors in those cases.
=> Fixes #136.

src/funit/core/TapListener.F90, src/funit/core/TestResult.F90
Previously this package was just a quick-and-dirty attempt to
demonstrate something could be done.    With this commit though
the output should be TAP conformant.
Currently there is no explicit equivalent of TAP "todo" tests. For now
users should make "todo" tests fail, e.g.,
@assert_that("todo", 1,equal_to(2))
Later I should add an  @todo annotation that would serve an analogous
purpose.  (Similar to @disable)
=> Fixing a few issues with TAP support.

include/driver.F90
The new approach in pFUnit 4.0 for the driver, treats optional
initialize() and finalize() as procedure pointer targets via
PFUNIT_EXTRA_INITIALIZE and PFUNIT_EXTRA_FINALIZE.  Within driver, a
procedure pointer is declared with an implicit interface, but this
approach requires that the target procedure have the EXTERNAL
attribute or be accessed through a module.
Unfortunately, one cannot simply always add EXTERNAL, because that it
conflicts if the user also uses PFUNIT_EXTRA_USE.   So users must not
mix and match.   Either the INITIALIZE and FINALIZE methods are given
through a module or they are external.
empty
=> Fixes #154 - EXTERNAL required

cmake/PFUNITConfig.cmake.in
OpenMP was not quite correctly exported for upstream projects.
Note: a similar fix for MPI is probably needed.
=> Fixes #164

ChangeLog.md, include/add_pfunit_ctest.cmake
Error was only exposed under some flavors of MPI.
(This should have been labeled as a hotfix.)
=> Fixes #170.

bin/funit/pFUnitParser.py, src/funit/core/TestMethod.F90, tests/funit-core/CMakeLists.txt, tests/funit-core/Test_TestMethod_before.pf, tests/funit-core/testSuites.inc
The constructor for TestMethod now allows setup without teardown and
vice-versa.  The othe overload for this constructor with non-optional
dummy arguments is deprecated, and the dummy argument spelling has
changed to avoid conflicts.  Users should obtain identical results
regardless of whether they use keyword association or not.   But it
is a bit subtle as to why.
=> Fixes #180.

src/funit/core/TestAnnotation.F90
This PR adds the specific typename StringTestAnnotationPair for the pair type contained within the StringTestAnnotationMap type. The change is analogous to Goddard-Fortran-Ecosystem/gFTL-shared#21 and Goddard-Fortran-Ecosystem/fArgParse#63.  These two PRs are also included in this PR as submodule updates.
This fixes a compile issue for pFUnit under the XLF compiler (see Goddard-Fortran-Ecosystem/pFUnit#208). It has been tested under Intel and GNU compilers.
=> Rename pair type within StringTestAnnotationMap to have type-specific name

.github/workflows/main.yml, tools/travis-install-mpi.sh
This commit adds GitHub Actions to pFUnit. 
There are a few interesting things here. First, due to the fact that [GitHub Actions virtual environments](https://github.com/actions/virtual-environments) are a bit more complete than most (see below to for links for each OS), there is no need to install almost anything. Even gfortran is included by default and [GitHub seems amenable to updating the images pretty quickly](https://github.com/actions/virtual-environments#software-guidelines) with issues to update them.
The only extra install was Open MPI as the `apt` or `brew` version would always run into issues as `mpi.mod` must/should be compiled per compiler. So, [actions/cache](https://github.com/actions/cache) was used to cache Open MPI builds. Note that the cache key is currently:
```yaml …
```
=> Add GitHub Actions

ChangeLog.md, cmake/GNU.cmake
Under WSL, GFortran-9 would crash immediately when runing some tests.
Exact cause has not been determined, but raising the optimization
level avoids the problem.   GFortran-10 appears to not have the issue.
=> Fixes #227 - WSL issue

ChangeLog.md, cmake/GNU.cmake, src/pfunit/core/MpiContext.F90
- Added flag that allows GFortran 10.x to compile with argument mismatches
in MPI layer.  This apparently is only an issue for some MPI flavors, with
others importing the correct interface variability via ```use mpi```.
@amklinv-nnl
=> Bugfix/workaround for gfortran 10.x

.github/workflows/main.yml, .travis.yml
This PR tries to fix both Travis CI and GitHub CI. Both move to use Ubuntu 20 by default, and Travis CI moves to the xcode12 osx.
=> Update Travis CI and GitHub CI

ChangeLog.md, include/CMakeLists.txt, include/add_pfunit_ctest.cmake, include/driver.F90.in
The `add_pfunit_ctest()` macro could fail under several not-so-rare
circumstances.  One way is for CMake to fail to build `OT
HER_SOURCES` before the driver as it cannot correctly analyze the
indirect Fortran `USE PFUNIT_EXTRA_INITIALIZE` statement.  The other
is when using paralle builds with multiple test suites using Intel
and the `-save-temps` flag.  Here the compiler would overwrite the
`driver.i90` in the build directory and produce confusing results.
The solution is to use Cmake `configure_file()` to preprocess the
driver directly on a per-suite basis.  This will allow CMake+FPP to
corretly analyze dependencies and avoid reuse of `driver.i90`.
=> Fixed problems with add_pfunit_ctest() macro

bin/funit/pFUnitParser.py, tests/funit-core/CMakeLists.txt, tests/funit-core/Test_Long_Subroutine_Name.pf
Create a subroutine test with the maximum fortran 2003 length (63 characters) and compile without errors.
Resolves #294
=> fix: allow for long subroutine names in allocate

documentation/CMakeLists.txt
Fix the cmake variable to match otherwise the doxygen build is not configured.
=> fix: correct documentation flag

cmake/CheckFortranSource.cmake
One issue with using pfunit via `add_subdirectory` in CMake is that there are some compiler-feature tests that rerun every time CMake needs to re-configure the project. This basically just makes them run only once (although fargparse needs a similar update I think).
One issue is that this probably breaks things if the user changes compiler that has different default kind sizes. In that case, the build directory needs to be cleared and the project reconfigured.
=> CMake: Don't rerun source-compilation tests if they've already run

cmake/CheckFortranSource.cmake
Embarrassingly, I hadn't tested #307 very well and it's not very robust. This fix should work better in all circumstances now
=> CMake: Fix for source-compilation tests not caching variables

CMakeLists.txt, ChangeLog.md, cmake/GNU.cmake
- Fix for OpenMP handling in `PFUNITCmake.cmake`. If you skip OpenMP, it is no
longer a dependency
- Allow GFortran to use longer lines.  (Impacts some upstream use cases.)
- Updated external modules that contain bugfixes.
- Changed `OTHER_SRCS` to `OTHER_SOURCES` in PFUNIT.mk.  The previous spelling
is deprecated, but preserved to keep backwards compatibility.
=> Fixes #329

include/add_pfunit_ctest.cmake
For some reason, when using `add_pfunit_ctest` in a subdirectory, `_[P]FUNIT_LIBRARIES` was empty, meaning the tests weren't getting compiled/linked properly.
`add_pfunit_test` uses `PFUNIT_LIBRARIES` directly, so follow that in `add_pfunit_ctest` too.
=> CMake: Fix linking tests in nested subdirectories

CMakeLists.txt, ChangeLog.md, include/pf_mpi_defines.fh, src/pfunit/CMakeLists.txt, src/pfunit/core/CMakeLists.txt, src/pfunit/core/MpiContext.F90, src/pfunit/core/MpiTestCase.F90, src/pfunit/core/pFUnit.F90, src/pfunit/pFUnit.F90, tests/pfunit/Test_MpiTestCase.F90
Closes #34 
Rather than the `pf_mpi_defines.fh` header, we could instead use add all the definitions directly to the `pf-mpi-defines` target for the same effect. The differences is that with the header we keep the set of "exposed" preprocessor macros minimal.
Note that this also relies on the F2008 ability to do `type (integer)` so that we can do the slightly nicer `type (PF_MPI_COMM_TYPE)`. It is possible to have the macro be `PF_MPI_COMM_TYPE=type(MPI_Comm)/integer` and use `PF_MPI_COMM_TYPE` directly in the code instead.
=> CMake: Add option to use MPI F08 module

ChangeLog.md, src/pfunit/CMakeLists.txt
Recent testing with the GFE repo showed that `make tests` seems to have a currently unexplained issue with the `pfunit-mpi-defines` target:
```
CMake Error at /Users/mathomp4/installed/MPI/gcc-gfortran-11.3.0/openmpi-4.1.3/Baselibs/7.4.0-TEST/Darwin/PFUNIT-4.4/cmake/PFUNITTargets.cmake:37 (message):
Some (but not all) targets in this export set were already defined.
Targets Defined: PFUNIT::funit;PFUNIT::pfunit
Targets not yet defined: PFUNIT::pfunit-mpi-defines
Call Stack (most recent call first):
/Users/mathomp4/installed/MPI/gcc-gfortran-11.3.0/openmpi-4.1.3/Baselibs/7.4.0-TEST/Darwin/PFUNIT-4.4/cmake/PFUNITConfig.cmake:113 (include)
yaFyaml/CMakeLists.txt:30 (find_package)
-- Configuring incomplete, errors occurred!
See also "/Users/mathomp4/Baselibs/ESMA-Baselibs-7.4.0-TEST/src/GFE/bu …
```
=> Add pfunit-mpi-defines ALIAS

CMakeLists.txt, ChangeLog.md, bin/funit/pFUnitParser.py
`pFUnitParser.py` was inadvertently make Python3 only with the use of the `pathlib` module. While we should all move to Python 3 (and pFUnit 5 might make that a requirement), for now, we return Python2 compatibility by using `os.path` mechanisms.
Also, we make the new matching test case-insensitive. Note as this is done with `.lower()` this is not Unicode safe, but Fortran doesn't really support Unicode in module names, so we are okay.
=> Restore Python2 compatibility in pFUnitParser.py

.github/workflows/main.yml, ChangeLog.md
This PR pins pFUnit to use CMake 3.24.3. This is in response to a current bug between CMake 3.25.0 and pFUnit, see https://gitlab.kitware.com/cmake/cmake/-/issues/24203
=> Pin CI to use CMake 3.24.3

.github/workflows/main.yml
use CMake abstract build commands for compactness and clarity
=> Use CMake abstract build commands

.github/workflows/main.yml, ChangeLog.md
From what I can tell, GitHub Actions images now have CMake 3.25.1. From my reading of the git log of CMake, this should have the fix for pFUnit's cmake issue seen earlier (see #399). 
This will be a good test!
NOTE: The changelog entry for this is weird as it talks about the changes from @scivision in #403, but until #401 gets in, the changelog isn't enforced.
=> Remove explicit CMake in CI

CMakeLists.txt, bin/CMakeLists.txt, bin/tests/CMakeLists.txt, cmake/CheckFortranSource.cmake, cmake/GNU.cmake, cmake/Intel.cmake, cmake/NAG.cmake, cmake/XL.cmake, include/add_pfunit_sources.cmake, src/funit/CMakeLists.txt, src/funit/asserts/CMakeLists.txt, src/pfunit/CMakeLists.txt, tests/pfunit/CMakeLists.txt
These updates fit with CMake >= 3.12 and avoid hard-coded flags or ambiguous syntax from CMake 2.x era. No change in behavior.
=> Cmake refactor

ChangeLog.md, include/add_pfunit_ctest.cmake
made tests added with add_pfunit_ctest verbose, s.t. --verbose is effectively passed through by ctest.
=> fix: verbose ctests

ChangeLog.md, include/add_pfunit_ctest.cmake
CTests offers the functionality to run only or exclude tests with certain labels with -L and -LE, respectively.
I added the possibility to add labels to CTests via the add_pfunit_ctest function with the new multi-argument option LABELS.
=> feat: ctest labels

CMakeLists.txt
For building pFUnit only the Fortran component of the MPI target is needed. Being more specific in the find_package call avoids warnings for the C component of MPI in some cases.
=> Only load Fortran COMPONENTS for find_package(MPI)

CMakeLists.txt
Using pFUnit via FetchContent in an downstream project leads to problems due to not defined PFUNIT_MPI_FOUND and similar variables which are used in the add_pfunit_test macro at build time. So if not configured as main project, two additional variables have to be set.
=> Bugfix for FetchContent usage

ChangeLog.md, include/add_pfunit_ctest.cmake
Should resolve issue #426. 
It seems that the it was sufficient to avoid adding basenames to the `test_sources_f90` list before all F90 files are set in `add_pfunit_sources` function
=> Restore consistent behaviour between `*_sources.cmake` and `*_ctest.cmake` 

src/pfunit/CMakeLists.txt
Dear authors,
I ran into this CMake error while compiling with MPI and with `BUILD_SHARED_LIB=ON`.
```
-- MPI enabled
-- OpenMP enabled
-- Using submodule /path/to/pFUnit/extern/fArgParse
-- Using submodule /path/to/pFUnit/extern/fArgParse/extern/gFTL-shared
-- Performing Test _LOGICAL_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _INT_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _ISO_INT8: SUCCESS (value=1)
-- Performing Test _ISO_INT16: SUCCESS (value=2)
-- Performing Test _ISO_INT32: SUCCESS (value=4)
-- Performing Test _ISO_INT64: SUCCESS (value=8)
-- Performing Test _REAL_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _DOUBLE_DEFAULT_KIND: SUCCESS (value=8)
-- Performing Test _ISO_REAL32: SUCCESS (value=4)
-- Performing Test _ISO_REAL64: SUCCESS (value=8)
-- Performing …
```
=> Cmake error when compiled with BUILD_SHARED_LIB=ON

CMakeLists.txt, ChangeLog.md, cmake/IntelLLVM.cmake
This PR adds the `-check uninit` flag for `ifx` as there is currently a bug with this (see https://github.com/HPC-Bugs/reproducers/tree/main/compiler/Fortran/ifx/allocatable)
=> Add uninit flag for ifx

ChangeLog.md, cmake/NAG.cmake
This PR adds `-quiet` to the NAG Fortran compiler flags. This flag will "[s]uppress the compiler banner and the summary line, so that only diagnostic messages will appear."
=> Add quiet flag for NAG Fortran

.github/workflows/main.yml, ChangeLog.md, tools/ci-install-mpi.sh
As `macos-11` is deprecated at GitHub Actions (and is ancient) and `macos-12` is also old, we remove them and add `macos-13` and `macos-14`.
We also fix up the Ubuntu tests as gcc 13 is no longer in Ubuntu 22
Finally, we add `gfortran-14` to the CI for Ubuntu 24
=> CI: Remove macos-11 and -12, add macos-13, -14; Add ubuntu 24, add gfortran-14

.github/workflows/main.yml, .gitignore, CMakeLists.txt, ChangeLog.md, bin/tests/inputs/MpiParameterizedTestCaseC.pf, bin/tests/inputs/MpiTestCaseB.pf, bin/tests/inputs/ParameterizedTestCaseB.pf, bin/tests/inputs/TestA.pf, bin/tests/inputs/TestCaseA.pf
These were found via CI testing in GFE (see https://github.com/Goddard-Fortran-Ecosystem/GFE/pull/36)
=> Fix up some ctest errors

ChangeLog.md, tests/fhamcrest/CMakeLists.txt, tests/funit-core/CMakeLists.txt
I recently experienced failure on a long-standing workflow (Ubuntu on GitHub) due to the CMake version being set too low (3.0) now deprecated in some files (`tests/fhamcrest/CMakeLists.txt` and `tests/funit-core/CMakeLists.txt`).
This PR updates the minimum version to `3.12` to match that in the main CMakeLists.txt and the minimum version specified by pFUnit's documentation.
I have tested my fork in the failing workflow (instead of cloning from Goddard) and can confirm it resolves the issues seen.
For reference the PR to our repository in which I do this is [here](https://github.com/Cambridge-ICCS/FTorch/pull/351)
=> Update minimum CMake version in subdirectories to 3.12.

ChangeLog.md, bin/funit/pFUnitParser.py
In our Windows setup, python `sysconfig.get_platform()` results in `win-amd64`.
So we get the wrong path separator in generated source files (`\` instead of `/`) which leads to compiler errors.
=> Fix windows line markers

.github/workflows/main.yml, ChangeLog.md, include/add_pfunit_ctest.cmake, include/add_pfunit_test.cmake
This PR has a CMake workaround for an ifx 2025.2 bug in their preprocessor, see https://community.intel.com/t5/Intel-Fortran-Compiler/Regression-with-fpp-2025-2-0/td-p/1703735
This bug will be fixed in ifx 2025.3, but there is a need to get ifx 2025.2 working (as it fixes bugs in other repos, e.g., fms).
Note: This should be taken in concert with:
- https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/pull/88
- https://github.com/Goddard-Fortran-Ecosystem/pFlogger/pull/145
cc: @climbfuji
---
As GitHub will soon drop support for macOS 13, we are updating our CI workflows to use macOS 15. Additionally, we are adding support for gfortran-15 to ensure compatibility with the latest Fortran compiler.
=> Fixes for ifx 2025.2 support

.github/workflows/main.yml, CMakeLists.txt, ChangeLog.md, tests/fhamcrest/CMakeLists.txt, tests/funit-core/CMakeLists.txt
This PR updates the CMake minimum version to 3.24. We choose this as internal use of GFE with MAPL uses 3.24 so we update here for consistency.
NOTE: This is sort of "above and beyond" #488 from @jatkinson1000 . However, internally with MAPL we set our CMake minimum to 3.24, so we are updating all of GFE for consistency.
=> Update CMake minimum version to 3.24
