.gitmodules, CMakeLists.txt
gFTL now lives in the same org as pFUnit.
=> Fixes #3.   Moved home for gFTL.

CMakeLists.txt, cmake/BuildSubmodule.cmake, src/core/CMakeLists.txt
I am sure this is still not really the "cmake way", but at
least it is simpler.
=> Refactoring logic for managing external dependencies.

.travis.yml
MPI tests cover serial case anyway.
=> Fixes #85   (simplify travis tests)

CMakeLists.txt, cmake/PFUNIT.mk.in, cmake/PFUNITConfig.cmake.in
- work in progress, but already can build several of the demos.
- needs documentation.
=> Improved macros for Unix make support.

cmake/PFUNITConfig.cmake.in
find_package() moved to earlier in config.
=> Fixes #98.

.gitignore, CMakeLists.txt, src/funit/FUnit.F90, src/funit/core/FUnit_Core.F90, src/funit/core/TapListener.F90, tests/funit-core/Test_TapListener.pf
Added an option -t <file> or --tap <file> to activate the tap
listener.  Tap output is sent to <file>.
=> Fixes #106.  Complete TapListener.

include/add_pfunit_sources.cmake
=> Fix cmake installation bug

bin/funit/pFUnitParser.py
Should now work Python-2.7 and Python-3.
=> Fixes test failures induced by Python-3 support.

README.md
Just a couple typos as I try to learn pFUnit 4
=> Spelling Fixes for README.md

.travis.yml, CMakeLists.txt, bin/CMakeLists.txt, bin/tests/CMakeLists.txt, src/funit/core/CMakeLists.txt, tests/CMakeLists.txt
* Use the homebrew addon
* Add `find_package(Python) to main `CMakeLists.txt`
* Remove `find_package(Python)` from subdirs
(Note: `FindPython.cmake` now no longer has a `REQUIRED` option.)
=> Various fixes for Travis.

bin/funit/pFUnitParser.py, src/funit/core/TestMethod.F90
Botched the push yesterday and only captured penultimate changes.
=> Fixes #180

ChangeLog.md, src/funit/FUnit.F90, src/pfunit/pFUnit.F90
Surprised I had not encountered this one.
=> Fixes #195 - command line broken with MPI

.travis.yml
& Build pFUnit with Debug-mode to get more information on failures.
=> Allow travis-ci failures on arm64

CMakeLists.txt, ChangeLog.md, cmake/BuildType.cmake, cmake/GNU.cmake, cmake/Intel.cmake, cmake/NAG.cmake, src/funit/core/TestMethod.F90, src/funit/fhamcrest/ArrayWrapper.tmpl, src/funit/fhamcrest/CMakeLists.txt, src/funit/fhamcrest/Every.F90, tests/fhamcrest/Test_Every.pf
Oddly these were mostly not tripping things in gfortran, but showed up
in force when restoring debug options under NAG.  (Lesson learned.)
=> Various minor bugfixes.

CMakeLists.txt, ChangeLog.md, src/funit/asserts/Assert_Real.tmpl
=> Fix for bug in assert for relatively equal.

.github/workflows/main.yml
I believe GCC 10 is now available from GitHub Actions. This PR will test it out.
=> Add GCC 10 to GitHub Actions For Ubuntu

.github/workflows/main.yml
Intel is offering now its compilers for free.
=> [GitHub-Actions] Add Intel compilers.

CMakeLists.txt, ChangeLog.md
Preparing for release  that corrects recent instability in the build.
=> Updated ChangeLog

.github/workflows/main.yml
This PR removes GCC 8 as @tclune says he's fine with it
=> Remove GCC 8 from CI

CMakeLists.txt, ChangeLog.md, src/funit/asserts/Assert_Integer.tmpl, tests/funit-core/Test_Assert_Integer.pf
Incorrect logic for AssertNotEqual for integers.
A unit test was added to cover this case.
=> Fixes #353

.github/workflows/changelog-enforcer.yml, ChangeLog.md
This PR adds a changelog enforcer to pFUnit.
=> Add changelog enforcer

.github/workflows/main.yml, ChangeLog.md
This is an attempt to fix the ifort CI.
=> Fix Intel Fortran CI

ChangeLog.md, src/funit/CMakeLists.txt, src/funit/core/AbstractPattern.F90, src/funit/core/ExceptionList.F90, src/funit/core/ExceptionVector.F90, src/funit/core/TestAnnotation.F90, src/funit/core/TestFailureVector.F90, src/funit/core/TestListenerVector.F90, src/funit/core/TestSuite.F90, src/funit/core/TestVector.F90, src/funit/fhamcrest/AllOf.F90, src/funit/fhamcrest/AnyOf.F90, src/funit/fhamcrest/BaseDescription.F90, src/funit/fhamcrest/MatcherVector.F90, src/funit/fhamcrest/SelfDescribingVector.F90
This PR builds upon #464 but brings in the needed updates from fArgParse.  Hoping it gets CI to pass..
=> Fixes #463

ChangeLog.md, bin/funit/pFUnitParser.py, src/funit/FUnit.F90, src/funit/core/RemoteRunner.F90, src/funit/core/RobustRunner.F90, src/pfunit/core/pFUnit.F90, src/pfunit/pFUnit.F90, tests/funit-core/robustTestSuite.F90
There were commits in main not in develop.
=> Missed GitFlow
